// assumptions: these are randomly generated by matter.js and x/y coordinates are updated for each created object
function PreciousObject(x, y) {
  this.x = x;
  this.y = y;
  this.preciousness = randomNumberGenerator(1, 5);
  this.createBody();
}

PreciousObject.prototype.xCoordinate = function () {
  return this.x;
};

PreciousObject.prototype.yCoordinate = function () {
  return this.y;
};

PreciousObject.prototype.getBody = function () {
  return this.body;
};

PreciousObject.prototype.createBody = function () {
  this.body = Matter.Bodies.rectangle(this.x, this.y, worldOptions.objectSize, worldOptions.objectSize);
};

PreciousObject.prototype.isOnGround = function () {
    if (this.y >= 240) {
      return true;
    }
};
