// assumptions: these are randomly generated by matter.js and x/y coordinates are updated for each created object
function PreciousObject(x, y) {
  this.x = x;
  this.y = y;
  this.preciousness = this.randomNumber(1, 5);
}

PreciousObject.prototype.xCoordinate = function () {
  return this.x;

};

PreciousObject.prototype.yCoordinate = function () {
  return this.y;
};

PreciousObject.prototype.isOnGround = function () {
    if (this.y >= 240) {
      return true;
    }
};

PreciousObject.prototype.randomNumber = function(max,min) {
  return Math.floor(Math.random()*(max-min) + min);
};
