// assumptions: these are randomly generated by matter.js and x/y coordinates are updated for each created object
function PreciousObject(x, y) {
  this.x = x;
  this.y = y;
  this.onFloor = false;
  this.rng = new RandomNumberGenerator();
  this.preciousness = this.rng.randomNumber(1, 5);
  this.createBody();
}

PreciousObject.prototype.xCoordinate = function () {
  return this.x;
};

PreciousObject.prototype.yCoordinate = function () {
  return this.y;
};

PreciousObject.prototype.getBody = function () {
  return this.body;
};

PreciousObject.prototype.createBody = function () {
  this.body = Matter.Bodies.rectangle(this.x, this.y, worldOptions.objectSize, worldOptions.objectSize, {label: 'object'});
};

PreciousObject.prototype.fallen = function () {
  this.onFloor = true;
};

PreciousObject.prototype.isOnFloor = function () {
  return this.onFloor;
};
